[options]
addons_path = /home/zen/O20/enterprise,/home/zen/O20/addons
admin_passwd = $pbkdf2-sha512$600000$QoixFkKo1bpXitGaE8L4Hw$WmW5c3RX08Un4AZFGvGA1ECbRfSEnwrO3PBqbS98JgoRFKzLfzcfSuLY7wVawp3oO6Du.4mBXBbm.2LP2kdgvw
db_host = 127.0.0.1
db_port = 5434
db_user = odoo
db_password = 1NN0R1@2026
http_interface = 0.0.0.0
http_port = 28070
gevent_port = 28073
data_dir = /home/zen/O20/data/tenants/innoria
log_level = info
dbfilter = ^innoria_prod$
db_name = innoria_prod
list_db = False
server_wide_modules = base,rpc,web,insilos_adapter
max_cron_threads = 1
